<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exemplo Cadastro</title>
</head>
<body>
    <h1>Cadastro de Usuário</h1>
    <form method="POST">
        <label>Nome</label>
        <input type="text" name="user_name">

        <label>Email</label>
        <input type="text" name="user_email">

        <label>Senha</label>
        <input type="text" name="user_password">
        <input type="submit" value="Salvar">
    </form>

    <h3>Lista de Usuários</h3>
    <table>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Email</th>
        </tr>
        <?php foreach($users as $user): ?>
            <tr>
                <td><?= $user->getId() ?></td>
                <td><?= $user->getName() ?></td>
                <td><?= $user->getEmail() ?></td>
            </tr>
        <?php endforeach ?>

        
    </table>
</body>
</html>